
language: "en_core_web_sm"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: RegexFeaturizer
- name: "SpacyEntityExtractor"
  # dimensions to extract
  dimensions: ["PERSON", "LOC", "ORG", "PRODUCT","PERCENT","MONEY","EVENT","GPE","NORP","PER"]

- name: "SpacyFeaturizer"
  # Specify what pooling operation should be used to calculate the vector of
  # the __CLS__ token. Available options: 'mean' and 'max'.
  pooling: "mean"
  
- name: CountVectorsFeaturizer
  analyzer: "word"
  min_df: 10
  stop_words: "english"
- name: DIETClassifier
  epochs: 300
  batch_size: 10
  random_seed: 10291
  entity_recognition: False
